name: D2AF
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - openbabel
  - xtb-python
  - openpyxl
  - pip:
    - matplotlib
    - tensorboard
    - torchvision
    - torch 
    - torchani
    - MLatom
    - scipy
    - pyh5md
    - statsmodels
    - h5py
    